### ISSUE TITLE
So many extensions fail due to 'possibly incompatible'

### ISSUE THREAD

**Issue by BruceChen2017** [ipython-contrib/jupyter_contrib_nbextensions#1037] opened 2017-08-03 03:05 UTC
I am using the latest version of jupyter notebook.How can I fix this?

**Comment by jcb91** [comment] 2017-08-03 09:11
Duplicate of #942. Essentially most should still work fine, and are just marked *possibly* incompatible because they haven't been tested. The configurator check box will allow you to enable them anyway.

**Comment by BruceChen2017** [comment] 2017-08-03 10:30
I got it.Because I check the option `disable configuration for nbextensions without explicit compatibility`,I can't try other extensions. @jcb91

**Closed** 2017-08-03 10:32 UTC

**Comment by queirozfcom** [comment] 2020-04-04 03:04
> I got it.Because I checked the option `disable configuration for nbextensions without explicit compatibility` before,I couldn't try other extensions. @jcb91

Yes!!!!!!
