### ISSUE TITLE
varInspector isn't compatible with Notebook 5.x?

### ISSUE THREAD

**Issue by andreas-h** [ipython-contrib/jupyter_contrib_nbextensions#1011] opened 2017-06-15 14:59 UTC
I cannot enable varInspector nbextension on my 5.x Notebook. The *Variable Inspector* entry is grayed out in the Nbextensions tab of the notebook.

Is there something I can do about this?

**Comment by juhasch** [comment] 2017-06-15 16:27
If you uncheck the checkbox for version checks on the configuration page, you can use the varInspector, see [here](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html).

The reason it is disabled is simply the compatibility has not been checked yet. Although I don't expect problems, if you try it please give us some feedback.

**Comment by GProtoZeroW** [comment] 2017-06-16 04:18
I have had to turn off varInspector; when I had it enabled in the latest version of jupyter it essentially caused sympy to not work.

**Comment by jcb91** [comment] 2017-06-16 12:39
> when I had it enabled in the latest version of jupyter it essentially caused sympy to not work

Could you elaborate on this? What exactly happens? I suspect sympy variables might benefit from a special handling by varInspector, similarly to numpy arrays...

**Comment by jfbercher** [comment] 2017-06-16 14:17
yes, I see no reason for an interference of varinspector with sympy. In 'python mode', varInspector only loads IPython core magics and json module.
Do you have an example and something reproducible?

**Comment by jfbercher** [comment] 2017-07-14 21:21
Compatibility fixed by #1016. 

I don't see anything regarding sympy compatibility or interference. It should be something unrelated with varInspector. If I miss something, open a new issue with indications to reproduce the problem.

**Closed by jfbercher** 2017-07-14 21:21 UTC
