### ISSUE TITLE
Solve Contrib Not Found Error (Jupyter contrib)

### ISSUE THREAD

**Issue by arbazkiraak** [ipython-contrib/jupyter_contrib_nbextensions#1152] opened 2017-11-02 19:40 UTC
> JUPYTER CONTRIB :+1: 

for [contrib] Not found  Error

You can install it from here: (Directly)
pip install https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/tarball/master

**Comment by jcb91** [comment] 2017-11-05 12:05
@arbazkiraak  I'm not really sure what you mean by any of this - do you mean you managed to somehow install the contrib repo *without* the configurator? Could you clarify a bit?

**Comment by jcb91** [comment] 2017-11-05 12:10
ah, unless you mean that running

    jupyter contrib

gave you an error?

**Comment by jcb91** [comment] 2017-12-06 16:31
closing this for want of more info. Feel free to reopen, but please add a little more explanation of what the problem is/was (what you did, what you expected to happen, what actually happened), along with versions of notebook & jupyter_contrib_nbextensions.

**Closed by jcb91** 2017-12-06 16:31 UTC
