### ISSUE TITLE
Editable pip install

### ISSUE THREAD

**Issue by andyneff** [ipython-contrib/jupyter_contrib_nbextensions#457] opened 2016-01-15 20:15 UTC
I tried using pip to install a git clone with the `-e` flag. While part of it installed, the bulk of it (the nb extenstions dir, and setting up nb extensions) did not.

I understand that this is not your standard python pip package, and that maybe some custom symlinks/junctions would have to be added to make all the files work, but it would be nice if this pip feature worked for development purposes.

**Comment by jcb91** [comment] 2016-06-13 23:14
this would be fixed by #626

**Comment by jcb91** [comment] 2016-07-30 01:40
should now be fixed using our new 2-part install method (note renamed repo):

    git clone https://github.com/ipython-contrib/jupyter_contrib_nbextensions.git jupyter_contrib_nbextensions
    pip install -e ./jupyter_contrib_nbextensions
    jupyter contrib nbextension install --user --symlink

where `jupyter contrib nbextension install` takes the same flags as `jupyter nbextension install`.

Closing, assuming fixed, but please reopen if it doesn't work as intended for you

**Closed by jcb91** 2016-07-30 01:40 UTC
