### ISSUE TITLE
 Link error: Error: post-link failed for: conda-forge::jupyter_nbextensions_configurator-0.2.3-py27_0

### ISSUE THREAD

**Issue by yunyundong** [ipython-contrib/jupyter_contrib_nbextensions#828] opened 2017-01-04 03:56 UTC
I want to install nbextensions for jupyte notebook, I used the command 

    conda install -c conda-forge jupyter_contrib_nbextensions

but it failed. there was a message:

    LinkError: Link error: Error: post-link failed for: conda-forge::jupyter_nbextensions_configurator-0.2.3-py27_0

besieds, I used pip to install:

    pip install https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master
    jupyter contrib nbextension install --system

in the process of install, there is no error messages. but after i restart the jupyte server, there is a 'nbextension' tab ,but it is empty, no extensions to be enabled. how can i do? by the way ,my anconada version is 4.2

by the way ,how can I uninstall the nbextensions clean? including remove the install packages.
Thanks in advance.

**Comment by jcb91** [comment] 2017-01-04 11:07
> there is a 'nbextension' tab ,but it is empty

Yes, this is provided not by this repo directly, but by the [jupyter_nbextensions_configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) package, which gets installed as a dependency. Using `pip uninstall <package>` doesn't remove packages installed as dependencies of `<package>` (see [this SO answer](http://stackoverflow.com/a/27713702)).

Therefore, to remove things completely, you'll have to do a little more work, and uninstall each of the dependencies which you no longer require. You could use the [pip-autoremove](https://github.com/invl/pip-autoremove) package, or use a [list of the dependencies as of today](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/8946d0779fb54165c3b466bda0c07650c7105166/setup.py#L64-L75). However, you probably want to keep some of the dependencies, as they'll be required by the notebook itself.

I'd recommend

    pip uninstall jupyter-contrib-core jupyter-highlight-selected-word jupyter-latex-envs jupyter-nbextensions-configurator psutil

To begin with

**Comment by tarokiritani** [comment] 2017-01-11 12:00
I have got a similar error when installing this repo.

I did
`conda install jupyter_contrib_nbextensions -c conda-forge`

and got this error:
`LinkError: Link error: Error: post-link failed for : conda-forge::jupyter_latex_envs-1.3.6-py35_0`

What I found a bit odd is I already have "jupyter-latex-envs" package installed on my environment.

**Comment by tt293** [comment] 2017-01-12 15:49
Facing the same issue as @tarokiritani, but on a py27 conda 4.2.13 environment.

**Comment by jcb91** [comment] 2017-01-13 16:58
So, something's clearly going wrong with our conda packaging/linking scripts, but I'm not yet sure what. The reason for the specific failure should be logged in the conda's `.messages.txt` file, which should be in `<conda_root>/envs/<env_name>/.messages.txt`, where `<conda_root>` is the root conda installation directory (normally `~/miniconda`, `~/miniconda3`, `~/anaconda`, `~/anaconda3` or similar), and `<env_name>` is the name of the conda env in which you attempted the install. If you could post the contents for that log file immediately after attempting the install, that'd be potentially really helpful. Thanks in advance :)

**Comment by jcb91** [comment] 2017-01-13 16:59
Also, which OS everyone is using might be relevant, and whether you see any nbextensions tab...

**Comment by jfbercher** [comment] 2017-01-13 17:20
@tarokiritani @tt293 
I can't reproduce with a fresh install of Anaconda on windows. I installed the nbextensions, it worked, then uninstalled, installed jupyter_nbextensions_configurator and jupyter_latex_envs, then the nbextensions and it also worked. So indeed, this seems to be something specific in your installation. Try to follow @jcb91 suggestions in order to try to isolate the reason.

**Comment by jcb91** [comment] 2017-01-13 17:22
My best guess is it's related to either permissions, or symlinks 😉

**Comment by tarokiritani** [comment] 2017-01-14 09:42
I use Windows 8.1 Enterprise. This installation error happened in one env, but in another, the installation went well.

Here is the content of .messages.txt after failed installation.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\kiritani\AppData\Local\Continuum\Anaconda3\envs\whisk_project2\lib\site-packages\notebook\nbextensions.py", line 225, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\kiritani\AppData\Local\Continuum\Anaconda3\envs\whisk_project2\lib\site-packages\notebook\nbextensions.py", line 1140, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\kiritani\AppData\Local\Continuum\Anaconda3\envs\whisk_project2\lib\site-packages\traitlets\utils\importstring.py", line 39, in import_item
    return __import__(parts[0])
  File "C:\Users\kiritani\AppData\Local\Continuum\Anaconda3\envs\whisk_project2\lib\site-packages\latex_envs\__init__.py", line 5, in <module>
    from . import latex_envs
  File "C:\Users\kiritani\AppData\Local\Continuum\Anaconda3\envs\whisk_project2\lib\site-packages\latex_envs\latex_envs.py", line 312, in <module>
    class LenvsLatexExporter(LatexExporter):
  File "C:\Users\kiritani\AppData\Local\Continuum\Anaconda3\envs\whisk_project2\lib\site-packages\latex_envs\latex_envs.py", line 318, in LenvsLatexExporter
    help="Remove headers and footers").tag(config=True)
AttributeError: 'Bool' object has no attribute 'tag'
```

**Comment by jcb91** [comment] 2017-01-14 10:42
Aha! Thanks @tarokiritani for that. I would not have guessed, but it seems that the latex_envs failure may be down to a traitlets version incompatibility. The `tag` API was introduced with traitlets 4.1, but the conda recipe doesn't actually specify a version (my fault!), so if you attempt to install into a pre-existing env which has traitlets 4.0, it wouldn't get upgraded, and you'd see this problem. Could you let me know the output of the following python command from the env which worked, along with the one which didn't, please?

```python
from traitlets import version_info; print(version_info)
```

**Comment by jcb91** [comment] 2017-01-14 10:47
I don't think that this is the exact source of the similar problem experienced by @yunyundong with the configurator though, since it doesn't use the `tag` API

**Comment by tarokiritani** [comment] 2017-01-14 19:26
In the env where installation succeeded, the output was (4, 3, 1). In the other env, the result was (4, 0, 0).

**Comment by jfbercher** [comment] 2017-01-14 19:49
So, It seems that @jcb91's diagnostic is correct. traitlets version >= 4.1 is needed for the installation to succeed. Just try to upgrade here with something like `conda install -f traitlets` or `pip install traitlets --upgrade`; On our side, we will have to explicitly include the requirement.

**Comment by jcb91** [comment] 2017-01-14 20:03
as @jfbercher suggests, to fix this for now, you just need to upgrade traitlets (in future we'll update the recipe to get the correct version in the first place without further effort). I'd suggest using 

    conda update traitlets

from the non-compatible env, to get the latest version compatible with all your other packages.

**Comment by tarokiritani** [comment] 2017-01-14 20:13
The installation worked fine after updating traitlets. Thanks for your quick support!

**Comment by jcb91** [comment] 2017-02-05 18:10
@yunyundong @tt293 does updating traitlets resolve this for you, or is this still a problem? I've now fixed the jupyter_latex_envs recipe (see https://github.com/conda-forge/jupyter_latex_envs-feedstock/issues/4) to require the correct traitlets version...

**Comment by jcb91** [comment] 2017-03-17 10:35
Ok, I'm going to close this as the `jupyter_latex_envs` recipe was fixed in https://github.com/conda-forge/jupyter_latex_envs-feedstock/pull/4. However, if @yunyundong or @tt293 (or anyone else) finds that the configurator post-link is still failing, please open a new issue at the configurator repo (https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator). Hope that makes sense!

**Closed by jcb91** 2017-03-17 10:35 UTC
Labels: conda, install

**Comment by megamindbrian** [comment] 2017-07-21 19:20
I am seeing this on the main installation ```conda install -f -c conda-forge jupyterlab```.  I am fairly new to conda and python but not so new to programming to know that this error message is awful:

```

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jupyterlab-0.25.2          |           py36_0         3.2 MB  conda-forge

The following NEW packages will be INSTALLED:

    jupyterlab: 0.25.2-py36_0 conda-forge

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
jupyterlab-0.2 100% |###############################| Time: 0:00:01   3.11 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[jupyterlab          ]|                                                  |   0%

LinkError: Link error: Error: post-link failed for: conda-forge::jupyterlab-0.25.2-py36_0

```

Ok... What exactly was the error then?  I don't understand why installers that go wrong don't just automatically show a verbose option.

**Comment by juhasch** [comment] 2017-07-22 10:10
You can try to add `-v` (up to three times) to your conda install command. This should give you more information. See `conda install -h`.

**Comment by megamindbrian** [comment] 2017-07-23 20:34
I eventually reinstalled conda and then installed pkg-config and jupyter lab individually. ```conda install jupyterlab``` never worked.
