### ISSUE TITLE
error: failed to load the snippets

### ISSUE THREAD

**Issue by weimindong2016** [ipython-contrib/jupyter_contrib_nbextensions#1236] opened 2018-02-12 18:39 UTC
System information
CentOS 7.4
JupyterHub 0.8.2

Issues to reproduce
1. followed the step1 and step 2 instructions on the link (https://github.com/ipython-contrib/jupyter_contrib_nbextensions) and installed nbextension successfully. 

   Note that in step 2, the following command is used
<pre>jupyter contrib nbextension install --symlink</pre>

2. configure the notebook extensions and enabled the extension "snippets". 

3. restarted the JupyterHub server and logged in successfully. 

4. Opened a notebook and found the error "failed to load snippets". Screenshot is included. 

Can someone share some help here? Thanks!

![005](https://user-images.githubusercontent.com/22266673/36113825-1cc76368-0ffc-11e8-8c5d-7ccd2c2f439c.png)

**Comment by jcb91** [comment] 2018-02-12 18:48
Most likely, this is a duplicate of #1210. If so, than you're seeing the bug that was fixed in #1212 (snippets was ignoring any `base_url` such as the one used by jupyterhub). This fix was applied after 0.4.0, so hasn't made it into a release yet...

**Comment by weimindong2016** [comment] 2018-02-12 19:50
Not exactly, even if I provide the absolute path in the code in main.js

<pre>
        $.getJSON("/usr/local/share/jupyter/nbextensions/snippets/snippets.json", function(data) {
            // Add the header as the top option, does nothing on click
            var option = $("<option></option>")
                         .attr("id", "snippet_header")
                         .text("Snippets");
            $("select#snippet_picker").append(option);

...
</pre>

The output of the log when a notebook is opened
<pre>
[I 2018-02-12 14:43:43.593 JupyterHub log:122] 302 GET /usr/local/share/jupyter/nbextensions/snippets/snippets.json → /hub/usr/local/share/jupyter/nbextensions/snippets/snippets.json (@192.168.1.22) 1.31ms
<b>[W 2018-02-12 14:43:43.690 JupyterHub log:122] 404 GET /hub/usr/local/share/jupyter/nbextensions/snippets/snippets.json (wdong@192.168.1.22) 16.90ms
[IPKernelApp] WARNING | Unknown error in handling startup files:</pre>
</pre>

**Comment by jcb91** [comment] 2018-02-12 19:58
Using an absolute local file path from the client (which has no notion of the server's local file system, even if they're in fact on the same machine) doesn't make sense. You need to use the variable `Jupyter.notebook.base_url` to form the correct path...

**Comment by weimindong2016** [comment] 2018-02-12 20:16
@jcb91:

thanks for the quick reply.  the absolute path was a blind shot because all the suggested fixes in the other two posts (1210, 1212) had failed. 

for example, if I choose the modify the main.js code as below as illustrated in the post 1210:
<pre>
$.getJSON(Jupyter.notebook.base_url+"nbextensions/snippets/snippets.json", function(data) {
     // Add the header as the top option, does nothing on click
    var option = $("<option></option>")
                 .attr("id", "snippet_header")
                 .text("Snippets");
    $("select#snippet_picker").append(option);

</pre>
There would be no error hints from the JupyterHub log output while the "failed to load snippets" error persisted. 
<pre>

[I 2018-02-12 15:07:50.151 SingleUserNotebookApp log:122] 200 GET /user/userxxx/api/contents/ch20_statistical_analytics_by_statsmodel.ipynb?type=notebook&_=1518466068376 (userxxx@192.168.1.22) 100.48ms
[I 2018-02-12 15:07:51.517 SingleUserNotebookApp kernelmanager:152] Kernel started: 35ef10c2-5b0c-43e2-be0f-937c38312f6a
[I 2018-02-12 15:07:51.520 SingleUserNotebookApp log:122] 201 POST /user/userxxx/api/sessions (userxxx@192.168.1.22) 41.39ms
[I 2018-02-12 15:07:51.653 SingleUserNotebookApp log:122] 200 GET /user/userxxx/api/contents/ch20_statistical_analytics_by_statsmodel.ipynb/checkpoints?_=1518466068377 (userxxx@192.168.1.22) 4.95ms
[IPKernelApp] WARNING | Unknown error in handling startup files:
[I 2018-02-12 15:07:52.945 SingleUserNotebookApp handlers:189] Adapting to protocol v5.1 for kernel 35ef10c2-5b0c-43e2-be0f-937c38312f6a
[I 2018-02-12 15:07:52.947 SingleUserNotebookApp log:122] 101 GET /user/userxxx/api/kernels/35ef10c2-5b0c-43e2-be0f-937c38312f6a/channels?session_id=889B0662542B40309E5DBD0AAB0CB162 (userxxx@192.168.1.22) 1361.41ms
[I 2018-02-12 15:07:57.113 SingleUserNotebookApp kernelmanager:190] Starting buffering for 35ef10c2-5b0c-43e2-be0f-937c38312f6a:889B0662542B40309E5DBD0AAB0CB162
[I 2018-02-12 15:07:58.123 SingleUserNotebookApp log:122] 200 GET /user/userxxx/api/config/notebook?_=1518466077587 (userxxx@192.168.1.22) 7.73ms
[I 2018-02-12 15:07:58.131 SingleUserNotebookApp log:122] 200 GET /user/userxxx/api/config/common?_=1518466077588 (userxxx@192.168.1.22) 6.24ms
</pre>

**Comment by jcb91** [comment] 2018-02-12 20:21
> There would be no error hints from the JupyterHub log output while the "failed to load snippets" error persisted on the UI.

In that case, perhaps a syntax error in the json file? Is there anything in the browser JavaScript console?

**Comment by weimindong2016** [comment] 2018-02-12 20:37
@jcb91 

Yes, you are right, Jcb91. There was an extra comma on one of the lines in the JSON file.  This file is more than 500 lines long. I guess it was missed from prior double checking.  

Thanks for the help!

**Closed** 2018-02-12 21:08 UTC
