### ISSUE TITLE
Keep codefolding / runtools formatting when exporting using nbconvert

### ISSUE THREAD

**Issue by ostrokach** [ipython-contrib/jupyter_contrib_nbextensions#198] opened 2015-03-11 21:30 UTC
I'm not sure if this has been suggested already, but I think it would be very useful to be able to keep notebook formatting, such as code folding and hidden input / output produced by `codefolding` and `runtools`, when exporting the notebook to html, pdf, slides, etc.

I often use the notebook to present my data, and I almost never want to make visible all the code that goes into making the plots. The best workaround that I have found so far is to use `nbconvert` templates, like the one given [here](http://www.damian.oquanta.info/posts/hide-the-input-cells-from-your-ipython-slides.html). Hovewer, it seems redundant to first format the notebook using `nbconvert` / `runtools` / etc. and then format it again using some template when making the pdf. 

Any suggestions on how this could be implemented? Thanks a lot.

**Comment by juhasch** [comment] 2015-03-11 22:36
This is actually already implemented, but currently not documented very well because things changed often before the 3.x release.

To achieve what you want, there are templates, pre- and postprocessors to tell nbconvert what to do. You also need to tell IPython where to find these.

In my configuration, I put the custom templates (.tpl files) in a `templates` subdirectory, and the pre-/postprocessors (codefolding.py, pymdpreprocessor.py, embed.py) implementing a special class in a `extension` subdirectory below the ipython directory.

My `ipython_nbconvert_config.py` looks like this:
```
from IPython.utils.path import get_ipython_dir
import os
import sys

ipythondir = get_ipython_dir()
extensions = os.path.join(ipythondir,'extensions') 
sys.path.append( extensions )

c = get_config()
c.Exporter.template_path = [os.path.join(ipythondir,'templates') ]
c.Exporter.template_file = 'hide_input_output.tpl'

c.Exporter.preprocessors = ['codefolding.CodeFoldingPreprocessor', 'pymdpreprocessor.PyMarkdownPreprocessor' ]
c.Exporter.postprocessors = ['embed.EmbedPostProcessor']
c.NbConvertApp.postprocessor = ['embed.EmbedPostProcessor']
```

**Comment by ostrokach** [comment] 2015-03-12 03:17
Thanks a lot for the reply!
I got `runtools` and `python-markdown` to work, but for some reason I can't get `codefolding` to work. I tried everything I could think of. 

My `.ipython/extensions` folder contains:

    codefolding.py
    embed.py
    nbextensions.py
    pymdpreprocessor.py

My `.ipython/templates` folder contains:

    hide_input_output.tpl
    nbextensions.html

My `ipython_nbconvert_config.py` file looks exactly like yours. Yet the output of `ipython nbconvert my_notebook.ipynb` has code-blocks that have not been touched by `codefolding`. Any suggestions?

-----

Also, on a different note, I think the wiki urgently needs to be updated, at least for someone running Anaconda Python 3 on Ubuntu 14.04. (I'm not sure if this is the right place to comment, but I can always edit the post later...). 

The general installation instructions are misleading and confusing. 

Running the code provided in [install the notebook extension repository](https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Home_3x#1install-the-notebook-extension-repository):

    import IPython.html.nbextensions as nb
    ext= 'https://github.com/ipython-contrib/IPython-notebook-extensions/archive/master.zip'
    nb.install_nbextension(ext)

gives an error:

    PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'

The demo code for [activating](https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Home_3x#2-automatically-loading-extensions) and [deactivating](https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Home_3x#3-deactivating-extensions) extensions is identical. (I think in both cases it's for activating `runtools`).

The `custom.js` template ([custom.example.js](https://raw.githubusercontent.com/ipython-contrib/IPython-notebook-extensions/master/custom.example.js)) doesn't work. Whenever you have subfolders, e.g.:

```javascript
    IPython.load_extensions('usability/codefolding/codefolding')
    IPython.load_extensions('usability/dragdrop/drag-and-drop')
    IPython.load_extensions('usability/runtools/runtools')
```

It should actually be:

```javascript
    IPython.load_extensions('usability/codefolding/main')
    IPython.load_extensions('usability/dragdrop/main')
    IPython.load_extensions('usability/runtools/main')
```

Or I think that's what it should be, because it didn't work for me otherwise.

**Comment by juhasch** [comment] 2015-03-14 11:50
The Wiki indeed needs some updating. Unfortunately, I am currently too busy to spend much time on Python. If you use Anaconda, take a look at the PR #194 for easier installation

Please open an issue for the `nb.install_nbextension(ext)` error in the IPython or Jupyter repo, this should be addressed there.

**Comment by ostrokach** [comment] 2015-03-14 20:50
OK, I'll open a separate issue for the `nb.install_nbextension(ext)` error.
Could you give me any hints on how to get started if I wanted to figure out why `codefolding` isn't working with `nbconvert`? I put in some `print` statements in `codefolding.py`, but those print statements don't get called when I open a notebook.

Thank you very much for your work!

**Comment by juhasch** [comment] 2015-03-15 18:45
You can use `self.log.info()` calls to print strings in the codefolding preprocessor.

**Comment by mlgill** [comment] 2015-06-10 16:10
I can confirm that the current version of runtools works for me with nbconvert from IPython version 3.1 for sending folded output to html. For me, the trick was remembering that I **ALSO** had to call the correct profile (for me, this profile was `notebook`) during nbconvert so that it doesn't use the default profile--a simple thing to overlook.

As an example, I put the files mentioned by @ostrokach into the `.ipython/extensions` and `.ipython/templates` directories (except I forgot to add `nbextensions.html` and apparently didn't need to). Then, I made the changes mentioned by @juhasch above to the file `ipython_nbconvert_config.py` in the directory `profile_notebook`. Last, I ran nbconvert as follows:

`ipython nbconvert --profile notebook --to html Name_of_Notebook.ipynb`

And it worked--all of the input cells that should have been hidden were!

This is a really slick extension and I'm sorry I didn't start playing with extensions sooner. Thanks for your work on this @juhasch.

**Comment by mlgill** [comment] 2015-06-10 16:28
FYI, I just tested the conversion to pdf and it doesn't work with this profile, but it does with my default profile and the same notebook.

The output when I use runtools is the exact contents of the file `hide_input_output.tpl` below--i.e. none of my data is inserted. I suspect nbconvert is not finding the parent template (full.tpl) even though it is part of the default set included with IPython. Unfortunately, I don't have time to investigate now.

```
{%- extends 'full.tpl' -%}

{% block input_group -%}
{%- if cell.metadata.hide_input -%}
{%- else -%}
{{ super() }}
{%- endif -%}
{% endblock input_group %}

{% block output_group -%}
{%- if cell.metadata.hide_output -%}
{%- else -%}
{{ super() }}
{%- endif -%}
{% endblock output_group %}
```

**Comment by aglavic** [comment] 2015-08-24 15:45
I ran into the same problem. The template files for html export and LaTeX export are not compatible.
You need to convert it to the correct .tplx format, something like this:

((*- extends 'report.tplx' -*))

((* block input_group -*))
((*- if cell.metadata.hide_input -*))
((*- else -*))
((( super() )))
((*- endif -*))
((* endblock input_group *))

((* block output_group -*))
((*- if cell.metadata.hide_output -*))
((*- else -*))
((( super() )))
((*- endif -*))
((* endblock output_group *))

**Comment by juhasch** [comment] 2016-09-06 19:22
Should be resolved by supplied templates.

**Closed by juhasch** 2016-09-06 19:22 UTC
