### ISSUE TITLE
spellchecker breaks markdown rendering when offline

### ISSUE THREAD

**Issue by janschulz** [ipython-contrib/jupyter_contrib_nbextensions#640] opened 2016-06-22 19:07 UTC
Today I tried to use the notebook in the train without internet access. The result was that the nbextension page was not available (blank page, no error in the log). 

[There was also a second error that when I tried to put a cell into markdown mode (both via the `esc - M` and via the menu) that I couldn't get it to show properly (it added an empty cell (which seems to be a copy of the current cell) and only displayed a '#' and I couldn't get any typed text to show up). No idea why this happend but as I was just on the way to an interview it was a bit scary...]

**Comment by jcb91** [comment] 2016-06-22 19:15
> as I was just on the way to an interview it was a bit scary

yikes! 😨 murphy's law strikes again!

Ok, that's weird, but the fact you get a blank page rather than a 404 implies it's a javascript error somewhere, presumably because something is attempting to fetch a js library from somewhere, then not properly handling the error from not finding it. Pretty sure I've used the nbextensions page offline without problems though, so I'm not sure what's causing that offhand. Any javascript console output? Notebook version? I guess it's possible (though admittedly unlikely) that it's some component of notebook which is attempting to fetch something, rather than the nbextensions repo code. Assuming it's not a notebook bug, the second error sounds unrelated, so it might be best to open another issue for that if it's still reproducible.

**Comment by janschulz** [comment] 2016-06-22 21:07
Right now, even with internet access, I can't get the nbextension page to display :-( Here are the errors from the nbextension page. 

```
TypeError: $ is not a function(…)
TypeError: Cannot read property 'extend' of undefined(…)
TypeError: $(...).data is not a function(…)
TypeError: Cannot read property 'build_page' of undefined(…)
```

I couldn't reproduce the markdown problem, i suspect some caching issues... Will try to deelte cache and report back

**Comment by jcb91** [comment] 2016-06-22 23:36
Aha! two separate problems.

The main one (blanks nbextensions page) is (I think) a duplicate of #627, essentially caused by a bug in notebook 4.2.1, and should have been fixed in #628 - is your install up-to-date?

The `Failed to load resource: net::ERR_NAME_NOT_RESOLVED` is coming (as you may well have guessed) from the specllchecker nbextension which is trying and failing to fetch dictionaries from the cdn. I guess this somehow causes the creation of a markdown cell to fail, which in turn means that the old cell doesn't get deleted, resulting in your duplicate cell (jupyter 'converts' cell types by creating a new one, then deleting the old one). I'll try to think of a more graceful failure mode...

**Comment by jcb91** [comment] 2016-06-24 18:20
(renamed to reflect the spellchecker issue)

**Comment by jcb91** [comment] 2016-07-29 23:41
@janschulz is this still happening?

**Comment by janschulz** [comment] 2016-08-22 17:01
I can't reproduce this anymore (no inet and loading the pages in a new incognito browser tab), so it seems to be fixed?

**Comment by jcb91** [comment] 2016-08-22 17:21
Ace :+1:

**Closed by jcb91** 2016-08-22 17:21 UTC
