### ISSUE TITLE
Hide Menubar not working 

### ISSUE THREAD

**Issue by rahulshekhar97** [ipython-contrib/jupyter_contrib_nbextensions#880] opened 2017-02-10 20:42 UTC
jupyter nbextension enable hide_header/main
Why is this command not working? what is the name of the extension?

**Comment by jcb91** [comment] 2017-02-10 23:55
You might find it easier to use the [jupyter_nbextensions_configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) to enable/disable nbextensions. I can't be certain without more information on exactly what you attempted to do and what feedback the commands you ran gave you, but I'm guessing that the problem is either 

 * you haven't installed using the current repository master (there hasn't yet been a pip or conda release containing hide_header)
 * you *did* install a version of the python package containing hide_header form the repository, but you didn't re-run the second part of the installation `jupyter contrib nbextension install [--user|--sys-prefix|system]`

Does that make sense?

**Comment by rahulshekhar97** [comment] 2017-02-17 18:17
It doesn't allow me to install the system part. It says permission not allowed

**Comment by jcb91** [comment] 2017-02-19 00:43
> It doesn't allow me to install the system part. It says permission not allowed

That's normal, admin privileges are usually required to write to the system-level config and data directories. If you want to install to system-level directories, you'll need to use `sudo` or the equivalent for your platform. However, __you only need to install using one of the `--user`, `--sys-prefix` or `--system` flags, you don't need to use each of them in turn. If one install went ok, you don't need the others__

**Comment by rahulshekhar97** [comment] 2017-02-24 20:39
One did, yet it didn't work

**Comment by rahulshekhar97** [comment] 2017-02-24 20:42
I tried installing all of them and it still didn't work

**Comment by bluss** [comment] 2017-02-28 12:16
Can you be more specific? Something like I did these steps: Expected this result: The result I got instead was:. Thanks

**Comment by jcb91** [comment] 2017-03-29 13:58
closing this in the absence of any further information - please reopen with further details if you're still having problems @rahulshekhar97

**Closed by jcb91** 2017-03-29 13:58 UTC
