### ISSUE TITLE
pip installation doesn't work a second time

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ipython-contrib/jupyter_contrib_nbextensions#558] opened 2016-03-29 00:15 UTC
So, I use Dropbox to sync my Jupyter setup between machines. Unfortunately, using the `pip install` approach on the second machine failed to successfully set up iPy-nb-ex:

    > pip install --upgrade https://github.com/ipython-contrib/IPython-notebook-extensions/archive/master.zip --user
    Collecting https://github.com/ipython-contrib/IPython-notebook-extensions/archive/master.zip
      Downloading https://github.com/ipython-contrib/IPython-notebook-extensions/archive/master.zip (9.5MB)
        100% |████████████████████████████████| 9.5MB 155kB/s 
    Requirement already up-to-date: …
    Requirement already up-to-date: …
    Requirement already up-to-date: …
    Installing collected packages: Python-contrib-nbextensions, setuptools
      Found existing installation: Python-contrib-nbextensions alpha
        Uninstalling Python-contrib-nbextensions-alpha:
          Successfully uninstalled Python-contrib-nbextensions-alpha
      Running setup.py install for Python-contrib-nbextensions ... done
    Successfully installed Python-contrib-nbextensions-alpha setuptools-20.3.1

Unfortunately, I still get:

<img width="639" alt="screen shot 2016-03-28 at 6 35 27 pm" src="https://cloud.githubusercontent.com/assets/200/14093497/e0a9c09c-f513-11e5-9677-af9406b33ecd.png">

Just reporting this, in case there's a way to fix this behavior (i.e. allow subsequent invocations of the `pip install` command to ‘fix’ broken or incomplete installations).

Meanwhile, and related: is there a sanctioned way to vendor these things into a git repository / config repo / dotfiles repo? Might I suggest that maybe the various extensions should be versioned separately, so they can be submoduled?

**Comment by jcb91** [comment] 2016-03-30 11:17
Hi there. Sorry to hear it's causing problems. Exactly what the problem is here will likely depend on what exactly

> I use Dropbox to sync my Jupyter setup between machines

means. What exactly is sync'ed on Dropbox? I'm thinking mainly of the fact that the nbextensions configuration page (`/nbextensions` url) is provided by a server extension, which must obviously exist on the server machine, but that the main jupyter server is told to _use_ the extension by its config file(s). So, it will make a difference whether those config files are part of your Dropbox sync. If they are, then you may find a slightly trickier situation on your hands - because the config file is modified by the `setup.py` installer (via the [`configure_nbextensions.py` script](https://github.com/ipython-contrib/IPython-notebook-extensions/blob/86c1d0fdf961b9baaf494d3a0313be5bdf6f41cd/configure_nbextensions.py)) to add the server extension's location to the python path. Thus, if your config files are sync'ed, you'll need the path to the server extension to be the same on each of you machines, or the jupyter server won't be able to import the extension.

I realize that this is a bit of a ridiculous way of arranging things, and have been working on a proper pip package (i.e. one which will avoid ugly hacks like having to alter `sys.path`), but I'm still fiddling with it for now (it's my [trav branch](https://github.com/jcb91/IPython-notebook-extensions/tree/trav) if you really want a look, but I'm still altering its history, so I'd advise not relying on anything there).

**Comment by jcb91** [comment] 2016-03-30 11:24
To list all config files in use by `jupyter notebook`, you can use the following python snippet

```
import os
from jupyter_core.paths import jupyter_config_path

for p in jupyter_config_path():
    for ext in '.py', '.json':
        conf_path = os.path.join(p, 'jupyter_notebook_config' + ext)
        if os.path.exists(conf_path):
            print(conf_path)
```

**Comment by jcb91** [comment] 2016-03-30 11:28
Obviously, if your python libraries are dropbox sync'ed, then the installation on the second machine is likely to do nothing, as the code will already be in place. Also, based on the log of your install, I'm not sure that the `configure_nbextensions.py` script actually got run - it's supposed to print a bunch of output, although the fact that it's run through pip may strip/redirect some of that. Anyway, if that's the case, then it's possible that you could fix your issue by simply running that `configure_nbextensions.py` script...

**Comment by jcb91** [comment] 2016-04-19 00:14
It's also possible (likely?!) that this was actually just a result of my stupid bug from #569, and thus a duplicate of #579, and should now have been fixed by #580...

**Comment by jcb91** [comment] 2016-04-19 00:23
> Might I suggest that maybe the various extensions should be versioned separately, so they can be submoduled?

Versioning each separately - yes that would, in many ways, make sense. There are a few extensions which have been grafted in from other repos, notably `scratchpad`, `latex_envs` and `highlighter` come to mind. The main downside would be distributing the work of fixing issues across many small repositories, along with the fact that at the moment we don't have a good way of managing dependencies. We will possible shortly switch to python packages, to align with notebook 4.2, and in future presumably move to npm along with notebook 5, and although git submodules might be ok, I've not used them enough to be comfortable setting that up from scratch.

**Comment by jcb91** [comment] 2016-07-30 01:32
closing as outdated, given our new installation method

**Closed by jcb91** 2016-07-30 01:32 UTC
